---
name: cs580s2020_lab04
break: true
fastfail: false
indent: 4
---
src:
    ProposalGraphs.tex:
        CountFileWords --count 200
        ConfirmFileExists
        MatchFileFragment --fragment "subsection" --count 2
        MatchFileFragment --fragment "begin{figure}" --count 2
        MatchFileFragment --fragment "caption" --count 2
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "Your Name" --count 0 --exact
        MatchFileFragment --fragment "Proposal Title" --count 0 --exact
        MatchFileFragment --fragment "Add your graph and descriptive text  here." --count 0 --exact
        # MatchFileRegex --regex "block|equation|theorem" --count 1
figures:
    graph1.png:
        ConfirmFileExists
    graph2.png:
        ConfirmFileExists
CountCommits --count 5
